# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Jonas Kersulis
tagline:          Power & Energy, Python & Julia
url:              kersulis.github.io
paginate:         1
baseurl:          /
author:
  name:           Jonas Kersulis
  url:            https://twitter.com/TonyKersulis
  email:          jonas.kersulis@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/kersulis/kersulis.github.io

pages_list:
  About: '/about'
  Archive: '/archive'
  # Feed: '/atom.xml'

colors:
  UmmaTan: '#cfc096'
  BurtonTowerBeige: '#9b9a6d'
  TheRockGray: '#989c97'
  ObservatoryWhite: '#e4e1df'
  AngellHallAsh: '#a79d96'
  LawQuadStone: '#655a52'
  HillBrown: '#7a121c'
  LSAOrange: '#cc6600'
  ArchwayIvy: '#7e732f'
  RackhamRoofGreen: '#83b2a8'
  CanhamPoolBlue: '#587abc'
  MatthaeiViolet: '#575294'



highlighter: pygments

markdown: redcarpet